from fastapi import APIRouter, Depends
from functools import lru_cache
from typing import Dict, Any, List, Union
from services.gemini_service import gemini_service
from backend.routes.auth import verify_token

router = APIRouter()

# Initialize the Gemini Client for insights from modular service
insight_client = gemini_service.get_client()

# Mock data for the dashboard to hit the ground running
MOCK_DATA: Dict[str, Dict[str, Union[List[str], List[int]]]] = {
    "turnout_by_year": {
        "labels": ['2016', '2018', '2020', '2022', '2024'],
        "data": [55, 49, 66, 52, 60]
    },
    "queries_by_topic": {
        "labels": ['Registration', 'Deadlines', 'Polling Stations', 'Candidates'],
        "data": [40, 25, 20, 15]
    }
}

@router.get(
    "/dashboard-data",
    response_model=Dict[str, Any],
    summary="Get Analytics Dashboard Data",
    description="Retrieves mock voter turnout and query data, along with a real-time AI insight generated by Gemini."
)
async def get_dashboard_data(state: str = "all", district: str = "all", current_user: str = Depends(verify_token)) -> Dict[str, Any]:
    """
    Returns data for the performance analytical dashboard.
    In a real application, this would query a Cloud SQL database using the state and district filters.

    Args:
        state (str): The state to filter by. Defaults to "all".
        district (str): The district to filter by. Defaults to "all".
        current_user (str): The authenticated user's username.

    Returns:
        Dict[str, Any]: Dashboard data including turnout, query breakdown, and an AI insight.
    """
    
    # Generate AI Insight based on the data
    insight_text: str = "AI Insights not available (API Key missing)."
    if insight_client:
        try:
            prompt: str = f"Given voter turnout data for state {state}: {MOCK_DATA['turnout_by_year']['data']} over years 2016-2024, generate a one sentence AI prediction or insight for engagement."
            response = insight_client.models.generate_content(
                model="gemini-2.5-flash",
                contents=prompt
            )
            insight_text = response.text
        except Exception:
            insight_text = "AI Insight could not be generated at this time."

    return {
        "status": "success",
        "state": state,
        "district": district,
        "turnout_data": MOCK_DATA["turnout_by_year"],
        "queries_data": MOCK_DATA["queries_by_topic"],
        "ai_insight": insight_text
    }

@lru_cache(maxsize=128)
def _get_cached_timeline(state: str) -> Dict[str, Any]:
    """
    Cached helper function for timeline data.
    
    Args:
        state (str): The state to get deadlines for.
        
    Returns:
        Dict[str, Any]: Mock election deadlines.
    """
    return {
        "status": "success",
        "state": state,
        "dates": {
            "registration": "October 20, 2026",
            "early_voting": "October 25, 2026",
            "election_day": "November 3, 2026"
        }
    }

@router.get(
    "/timeline",
    response_model=Dict[str, Any],
    summary="Get Election Timeline",
    description="Returns state-specific election deadlines."
)
async def get_timeline(state: str, current_user: str = Depends(verify_token)) -> Dict[str, Any]:
    """
    Returns mock timeline deadlines for a given state, utilizing server-side caching.
    
    Args:
        state (str): The state abbreviation.
        current_user (str): The authenticated user.
        
    Returns:
        Dict[str, Any]: Dates for registration and voting.
    """
    return _get_cached_timeline(state)
